### ISSUE TITLE
"Highlight all" turns off by itself

### ISSUE THREAD

**Issue by hmijail** [Quicksaver/FindBar-Tweak#274] opened 2016-10-03 15:15 UTC
Firefox 50b3, though I have been seeing this for some time already (a couple of weeks?); Mac OS X 10.12.
Press Cmd+F to search, make sure "Highlight All" is pressed, type something. It gets searched and highlighted as expected. 
Press Cmd+F again. The find bar disappears, or if you moved into a text box, focus moves to the find bar again. But in both cases, the "Highlight All" button turns off.

The checkbox "Highlight all matches by default" in the extension preferences is checked, but unchecking it doesn't change the turning-off behavior.

**Comment by Kinematics** [comment] 2016-10-12 16:44
This also impacts the quickfind, in that quickfind no longer highlights all matches at all, without an obvious reason why, since the `Highlight All` button doesn't exist on the quickfind bar.

**Comment by HYBRID-BEING** [comment] 2016-12-04 07:53
Duplicate of issue #279

**Closed** 2016-12-06 22:05 UTC

**Comment by Quicksaver** [comment] 2016-12-08 01:23
All issues should be fixed in [beta version 2.1.11b1](https://github.com/Quicksaver/FindBar-Tweak/releases/tag/v2.1.11b1). Please give it a try and let me know if you still have any problems.
