### ISSUE TITLE
Highlight all etc

### ISSUE THREAD

**Issue by merula123** [Quicksaver/FindBar-Tweak#283] opened 2016-11-28 23:03 UTC
1. "Highlight all" does not work anymore

2. Items are not shown in the scrollbar anymore (before they were and in colour, too) 

Maybe more problems (because of a FF update ?), I just noticed these 2 things since today

**Comment by LafinJack** [comment] 2016-11-29 20:21
This happened to me after FF 50. While highlight all still works for me, I have to reenable it every time I enable the find bar, even though I have default highlight all enabled in the options.

**Comment by HYBRID-BEING** [comment] 2016-12-04 07:54
Duplicate of issue #279

**Comment by Quicksaver** [comment] 2016-12-06 22:04
Actually a duplicate of #263. Well... they both pretty much have the same cause.

**Closed by Quicksaver** 2016-12-06 22:04 UTC
Labels: duplicate
